In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv('gurgaon_properties_post_feature_selection_v2.csv').drop(columns=['store room','floor_category','balcony'])

In [3]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,flat,sector 104,4.45,4,5,Relatively New,7222.0,0,1,Medium
1,flat,sector 86,1.26,3,3,Moderately Old,1747.0,1,1,Medium
2,flat,sector 9a,1.50,4,3,Relatively New,1833.0,0,0,Low
3,flat,sector 37d,0.75,2,2,Moderately Old,1410.0,0,1,Medium
4,flat,sector 86,1.45,3,2,Relatively New,1480.0,0,2,Medium

In [4]:
# 0 -> unfurnished
# 1 -> semifurnished
# 2 -> furnished

# Numerical = bedRoom, bathroom, built_up_area, servant room
# Ordinal = property_type, furnishing_type, luxury_category 
# OHE = sector, agePossession

In [5]:
df['agePossession'] = df['agePossession'].replace(
    {
        'Relatively New':'new',
        'Moderately Old':'old',
        'New Property' : 'new',
        'Old Property' : 'old',
        'Under Construction' : 'under construction'
    }
)

In [6]:
df['agePossession'].unique()

array(['new', 'old', 'under construction'], dtype=object)

In [7]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,flat,sector 104,4.45,4,5,new,7222.0,0,1,Medium
1,flat,sector 86,1.26,3,3,old,1747.0,1,1,Medium
2,flat,sector 9a,1.50,4,3,new,1833.0,0,0,Low
3,flat,sector 37d,0.75,2,2,old,1410.0,0,1,Medium
4,flat,sector 86,1.45,3,2,new,1480.0,0,2,Medium

In [8]:
df['property_type'] = df['property_type'].replace({'flat':0,'house':1})

C:\Users\virat\AppData\Local\Temp\ipykernel_22020\71934247.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['property_type'] = df['property_type'].replace({'flat':0,'house':1})

In [9]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,0,sector 104,4.45,4,5,new,7222.0,0,1,Medium
1,0,sector 86,1.26,3,3,old,1747.0,1,1,Medium
2,0,sector 9a,1.50,4,3,new,1833.0,0,0,Low
3,0,sector 37d,0.75,2,2,old,1410.0,0,1,Medium
4,0,sector 86,1.45,3,2,new,1480.0,0,2,Medium

In [10]:
df['luxury_category'] = df['luxury_category'].replace({'Low':0,'Medium':1,'High':2})

C:\Users\virat\AppData\Local\Temp\ipykernel_22020\2576796079.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['luxury_category'] = df['luxury_category'].replace({'Low':0,'Medium':1,'High':2})

In [11]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,0,sector 104,4.45,4,5,new,7222.0,0,1,1
1,0,sector 86,1.26,3,3,old,1747.0,1,1,1
2,0,sector 9a,1.50,4,3,new,1833.0,0,0,0
3,0,sector 37d,0.75,2,2,old,1410.0,0,1,1
4,0,sector 86,1.45,3,2,new,1480.0,0,2,1

In [12]:
new_df = pd.get_dummies(df,columns=['sector','agePossession'],drop_first=True)

In [13]:
X = new_df.drop(columns=['price'])
y = new_df['price']

In [14]:
y_log = np.log1p(y)

In [15]:
y_log

0       1.695616
1       0.815365
2       0.916291
3       0.559616
4       0.896088
          ...
3549    0.717840
3550    0.875469
3551    0.336472
3552    1.081805
3553    0.792993
Name: price, Length: 3554, dtype: float64

In [16]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [17]:
X_scaled

array([[-0.51717989,  0.72860975,  1.19490906, ..., -0.05571996,
        -0.6074778 , -0.19092872],
       [-0.51717989, -0.07432949, -0.18456367, ..., -0.05571996,
         1.64615069, -0.19092872],
       [-0.51717989,  0.72860975, -0.18456367, ..., -0.05571996,
        -0.6074778 , -0.19092872],
       ...,
       [-0.51717989, -0.87726873, -0.87430004, ..., -0.05571996,
        -0.6074778 , -0.19092872],
       [ 1.9335632 , -0.07432949,  1.19490906, ..., -0.05571996,
         1.64615069, -0.19092872],
       [-0.51717989, -0.07432949, -0.18456367, ..., -0.05571996,
         1.64615069, -0.19092872]], shape=(3554, 121))

In [18]:
X_scaled = pd.DataFrame(X_scaled , columns = X.columns)

In [19]:
X_scaled

,property_type,bedRoom,bathroom,built_up_area,servant room,furnishing_type,luxury_category,sector_gwal pahari,sector_manesar,sector_sector 1,...,sector_sector 92,sector_sector 93,sector_sector 95,sector_sector 99,sector_sector 99a,sector_sector 9a,sector_sohna road,sector_sohna road road,agePossession_old,agePossession_under construction
0,-0.517180,0.728610,1.194909,4.407356,-0.747968,0.430655,0.444313,-0.071348,-0.044424,-0.092266,...,-0.170153,-0.050386,-0.125375,-0.058206,-0.092266,-0.053119,-0.211375,-0.05572,-0.607478,-0.190929
1,-0.517180,-0.074329,-0.184564,-0.094154,1.336956,0.430655,0.444313,-0.071348,-0.044424,-0.092266,...,-0.170153,-0.050386,-0.125375,-0.058206,-0.092266,-0.053119,-0.211375,-0.05572,1.646151,-0.190929
2,-0.517180,0.728610,-0.184564,-0.023446,-0.747968,-1.458910,-0.979571,-0.071348,-0.044424,-0.092266,...,-0.170153,-0.050386,-0.125375,-0.058206,-0.092266,18.825515,-0.211375,-0.05572,-0.607478,-0.190929
3,-0.517180,-0.877269,-0.874300,-0.371233,-0.747968,0.430655,0.444313,-0.071348,-0.044424,-0.092266,...,-0.170153,-0.050386,-0.125375,-0.058206,-0.092266,-0.053119,-0.211375,-0.05572,1.646151,-0.190929
4,-0.517180,-0.074329,-0.874300,-0.313680,-0.747968,2.320220,0.444313,-0.071348,-0.044424,-0.092266,...,-0.170153,-0.050386,-0.125375,-0.058206,-0.092266,-0.053119,-0.211375,-0.05572,-0.607478,-0.190929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3549,-0.517180,-0.074329,0.505173,0.113861,1.336956,-1.458910,0.444313,-0.071348,-0.044424,-0.092266,...,-0.170153,-0.050386,-0.125375,-0.058206,-0.092266,-0.053119,-0.211375,-0.05572,-0.607478,-0.190929
3550,-0.517180,-0.074329,-0.184564,-0.386033,-0.747968,-1.458910,1.868197,-0.071348,-0.044424,-0.092266,...,-0.170153,-0.050386,-0.125375,-0.058206,-0.092266,-0.053119,-0.211375,-0.05572,-0.607478,-0.190929
3551,-0.517180,-0.877269,-0.874300,-0.935258,-0.747968,2.320220,-0.979571,-0.071348,-0.044424,-0.092266,...,-0.170153,-0.050386,-0.125375,-0.058206,-0.092266,-0.053119,-0.211375,-0.05572,-0.607478,-0.190929
3552,1.933563,-0.074329,1.194909,-0.774108,-0.747968,0.430655,-0.979571,-0.071348,-0.044424,-0.092266,...,-0.170153,-0.050386,-0.125375,-0.058206,-0.092266,-0.053119,-0.211375,-0.05572,1.646151,-0.190929
3553,-0.517180,-0.074329,-0.184564,-0.122109,-0.747968,-1.458910,0.444313,-0.071348,-0.044424,-0.092266,...,-0.170153,-0.050386,-0.125375,-0.058206,-0.092266,-0.053119,-0.211375,-0.05572,1.646151,-0.190929

In [20]:
X_scaled.columns.to_list()

['property_type',
 'bedRoom',
 'bathroom',
 'built_up_area',
 'servant room',
 'furnishing_type',
 'luxury_category',
 'sector_gwal pahari',
 'sector_manesar',
 'sector_sector 1',
 'sector_sector 102',
 'sector_sector 103',
 'sector_sector 104',
 'sector_sector 105',
 'sector_sector 106',
 'sector_sector 107',
 'sector_sector 108',
 'sector_sector 109',
 'sector_sector 10a',
 'sector_sector 11',
 'sector_sector 110',
 'sector_sector 111',
 'sector_sector 112',
 'sector_sector 113',
 'sector_sector 12',
 'sector_sector 13',
 'sector_sector 14',
 'sector_sector 15',
 'sector_sector 17',
 'sector_sector 17a',
 'sector_sector 17b',
 'sector_sector 2',
 'sector_sector 21',
 'sector_sector 22',
 'sector_sector 23',
 'sector_sector 24',
 'sector_sector 25',
 'sector_sector 26',
 'sector_sector 27',
 'sector_sector 28',
 'sector_sector 3',
 'sector_sector 3 phase 2',
 'sector_sector 3 phase 3 extension',
 'sector_sector 30',
 'sector_sector 31',
 'sector_sector 33',
 'sector_sector 36',
 'sector_sector 36a',
 'sector_sector 37',
 'sector_sector 37c',
 'sector_sector 37d',
 'sector_sector 38',
 'sector_sector 39',
 'sector_sector 4',
 'sector_sector 40',
 'sector_sector 41',
 'sector_sector 43',
 'sector_sector 45',
 'sector_sector 46',
 'sector_sector 47',
 'sector_sector 48',
 'sector_sector 49',
 'sector_sector 5',
 'sector_sector 50',
 'sector_sector 51',
 'sector_sector 52',
 'sector_sector 53',
 'sector_sector 54',
 'sector_sector 55',
 'sector_sector 56',
 'sector_sector 57',
 'sector_sector 58',
 'sector_sector 59',
 'sector_sector 6',
 'sector_sector 60',
 'sector_sector 61',
 'sector_sector 62',
 'sector_sector 63',
 'sector_sector 63a',
 'sector_sector 65',
 'sector_sector 66',
 'sector_sector 67',
 'sector_sector 67a',
 'sector_sector 68',
 'sector_sector 69',
 'sector_sector 7',
 'sector_sector 70',
 'sector_sector 70a',
 'sector_sector 71',
 'sector_sector 72',
 'sector_sector 73',
 'sector_sector 74',
 'sector_sector 76',
 'sector_sector 77',
 'sector_sector 78',
 'sector_sector 79',
 'sector_sector 8',
 'sector_sector 80',
 'sector_sector 81',
 'sector_sector 82',
 'sector_sector 82a',
 'sector_sector 83',
 'sector_sector 84',
 'sector_sector 85',
 'sector_sector 86',
 'sector_sector 88a',
 'sector_sector 88b',
 'sector_sector 89',
 'sector_sector 9',
 'sector_sector 90',
 'sector_sector 91',
 'sector_sector 92',
 'sector_sector 93',
 'sector_sector 95',
 'sector_sector 99',
 'sector_sector 99a',
 'sector_sector 9a',
 'sector_sohna road',
 'sector_sohna road road',
 'agePossession_old',
 'agePossession_under construction']

In [21]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(LinearRegression(), X_scaled, y_log, cv=kfold, scoring='r2')

In [22]:
scores.mean() , scores.std()

(np.float64(0.8530446592832444), np.float64(0.018318498672489324))

In [23]:
lr = LinearRegression()
ridge = Ridge(alpha=0.0001)

In [24]:
lr.fit(X_scaled,y_log)

LinearRegression()

In [25]:
ridge.fit(X_scaled,y_log)

Ridge(alpha=0.0001)

In [27]:
coef_df = pd.DataFrame(ridge.coef_.reshape(1,121),columns=X.columns).stack().reset_index().drop(columns=['level_0']).rename(columns={'level_1':'feature',0:'coef'})

In [28]:
coef_df

                              feature      coef
0                       property_type  0.120979
1                             bedRoom  0.054727
2                            bathroom  0.066372
3                       built_up_area  0.208668
4                        servant room  0.049797
..                                ...       ...
116                  sector_sector 9a -0.006014
117                 sector_sohna road -0.031702
118            sector_sohna road road -0.010527
119                 agePossession_old -0.007731
120  agePossession_under construction  0.003525

[121 rows x 2 columns]

In [29]:
# 1. Import necessary libraries
import statsmodels.api as sm

# 2. Add a constant to X
X_with_const = sm.add_constant(X_scaled)

# 3. Fit the model
model = sm.OLS(y_log, X_with_const).fit()

# 4. Obtain summary statistics
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.865
Model:                            OLS   Adj. R-squared:                  0.861
Method:                 Least Squares   F-statistic:                     182.1
Date:                Mon, 06 Apr 2026   Prob (F-statistic):               0.00
Time:                        16:42:31   Log-Likelihood:                 592.99
No. Observations:                3554   AIC:                            -942.0
Df Residuals:                    3432   BIC:                            -188.5
Df Model:                         121
Covariance Type:            nonrobust
=====================================================================================================
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
const                                 1.0464      0.003    299.346      0.000       1.040       1.053
property_type                         0.1210      0.005     22.644      0.000       0.111       0.131
bedRoom                               0.0547      0.007      8.276      0.000       0.042       0.068
bathroom                              0.0664      0.007      9.680      0.000       0.053       0.080
built_up_area                         0.2087      0.005     41.211      0.000       0.199       0.219
servant room                          0.0498      0.005     10.996      0.000       0.041       0.059
furnishing_type                      -0.0002      0.004     -0.048      0.962      -0.008       0.007
luxury_category                       0.0070      0.004      1.753      0.080      -0.001       0.015
sector_gwal pahari                    0.0090      0.006      1.416      0.157      -0.003       0.021
sector_manesar                       -0.0111      0.005     -2.309      0.021      -0.021      -0.002
sector_sector 1                      -0.0223      0.008     -2.886      0.004      -0.037      -0.007
sector_sector 102                     0.0240      0.013      1.812      0.070      -0.002       0.050
sector_sector 103                    -0.0046      0.009     -0.529      0.597      -0.022       0.013
sector_sector 104                 -3.543e-05      0.011     -0.003      0.997      -0.021       0.021
sector_sector 105                    -0.0213      0.007     -3.196      0.001      -0.034      -0.008
sector_sector 106                    -0.0013      0.008     -0.153      0.878      -0.018       0.015
sector_sector 107                    -0.0156      0.010     -1.529      0.126      -0.036       0.004
sector_sector 108                     0.0145      0.010      1.436      0.151      -0.005       0.034
sector_sector 109                     0.0230      0.012      1.911      0.056      -0.001       0.047
sector_sector 10a                     0.0042      0.005      0.877      0.380      -0.005       0.014
sector_sector 11                     -0.0168      0.006     -2.727      0.006      -0.029      -0.005
sector_sector 110                     0.0070      0.007      1.011      0.312      -0.007       0.021
sector_sector 111                     0.0156      0.007      2.288      0.022       0.002       0.029
sector_sector 112                     0.0298      0.007      4.270      0.000       0.016       0.043
sector_sector 113                     0.0312      0.009      3.511      0.000       0.014       0.049
sector_sector 12                     -0.0215      0.008     -2.718      0.007      -0.037      -0.006
sector_sector 13                     -0.0137      0.005     -2.633      0.008      -0.024      -0.003
sector_sector 14                      0.0274      0.006      4.275      0.000       0.015       0.040
sector_sector 15                      0.0025      0.005      0.526      0.599      -0.007       0.012
sector_sector 17                      0.0059      0.005      1.256      0.209      -0.003       0.015
sector_sector 17a                     0.0035      0.004      0.931      0.352      -0.004       0.011
sector_sector 17b                     0.0129      0.004      3.115      0.002       0.005       0.021
sector_sector 2                       0.0041      0.010      0.395      0.693      -0.016       0.024
sector_sector 21                     -0.0104      0.005     -2.227      0.026      -0.020      -0.001
sector_sector 22                      0.0351      0.007      5.326      0.000       0.022       0.048
sector_sector 23                      0.0011      0.006      0.197      0.844      -0.010       0.012
sector_sector 24                      0.0168      0.007      2.526      0.012       0.004       0.030
sector_sector 25                      0.0557      0.008      6.586      0.000       0.039       0.072
sector_sector 26                      0.0723      0.009      8.273      0.000       0.055       0.089
sector_sector 27                      0.0066      0.004      1.665      0.096      -0.001       0.014
sector_sector 28                      0.0399      0.009      4.658      0.000       0.023       0.057
sector_sector 3                      -0.0139      0.007     -1.961      0.050      -0.028   -9.91e-07
sector_sector 3 phase 2              -0.0119      0.005     -2.545      0.011      -0.021      -0.003
sector_sector 3 phase 3 extension    -0.0154      0.005     -2.977      0.003      -0.026      -0.005
sector_sector 30                      0.0058      0.004      1.285      0.199      -0.003       0.015
sector_sector 31                      0.0216      0.005      4.064      0.000       0.011       0.032
sector_sector 33                      0.0263      0.011      2.461      0.014       0.005       0.047
sector_sector 36                     -0.0078      0.005     -1.441      0.150      -0.018       0.003
sector_sector 36a                     0.0095      0.005      1.745      0.081      -0.001       0.020
sector_sector 37                     -0.0016      0.004     -0.424      0.672      -0.009       0.006
sector_sector 37c                    -0.0132      0.010     -1.390      0.165      -0.032       0.005
sector_sector 37d                     0.0003      0.010      0.032      0.974      -0.020       0.021
sector_sector 38                      0.0111      0.005      2.084      0.037       0.001       0.022
sector_sector 39                      0.0019      0.005      0.352      0.725      -0.009       0.013
sector_sector 4                      -0.0233      0.009     -2.550      0.011      -0.041      -0.005
sector_sector 40                      0.0069      0.005      1.524      0.128      -0.002       0.016
sector_sector 41                      0.0161      0.005      2.941      0.003       0.005       0.027
sector_sector 43                      0.0592      0.010      5.820      0.000       0.039       0.079
sector_sector 45                      0.0266      0.005      5.310      0.000       0.017       0.036
sector_sector 46                      0.0150      0.005      2.730      0.006       0.004       0.026
sector_sector 47                      0.0118      0.006      1.931      0.054      -0.000       0.024
sector_sector 48                      0.0525      0.010      5.280      0.000       0.033       0.072
sector_sector 49                      0.0299      0.009      3.285      0.001       0.012       0.048
sector_sector 5                      -0.0041      0.005     -0.869      0.385      -0.013       0.005
sector_sector 50                      0.0699      0.010      6.694      0.000       0.049       0.090
sector_sector 51                     -0.0008      0.005     -0.166      0.868      -0.010       0.009
sector_sector 52                      0.0038      0.006      0.654      0.513      -0.008       0.015
sector_sector 53                      0.0479      0.006      8.188      0.000       0.036       0.059
sector_sector 54                      0.0448      0.007      6.136      0.000       0.030       0.059
sector_sector 55                      0.0119      0.005      2.236      0.025       0.001       0.022
sector_sector 56                      0.0101      0.010      1.038      0.299      -0.009       0.029
sector_sector 57                      0.0239      0.007      3.406      0.001       0.010       0.038
sector_sector 58                      0.0231      0.005      4.789      0.000       0.014       0.033
sector_sector 59                      0.0321      0.005      6.489      0.000       0.022       0.042
sector_sector 6                      -0.0172      0.005     -3.144      0.002      -0.028      -0.006
sector_sector 60                      0.0232      0.006      3.862      0.000       0.011       0.035
sector_sector 61                      0.0372      0.009      4.294      0.000       0.020       0.054
sector_sector 62                      0.0424      0.006      6.948      0.000       0.030       0.054
sector_sector 63                      0.0339      0.006      5.800      0.000       0.022       0.045
sector_sector 63a                     0.0250      0.006      4.207      0.000       0.013       0.037
sector_sector 65                      0.0700      0.012      5.800      0.000       0.046       0.094
sector_sector 66                      0.0514      0.009      5.876      0.000       0.034       0.069
sector_sector 67                      0.0395      0.009      4.265      0.000       0.021       0.058
sector_sector 67a                     0.0076      0.007      1.132      0.258      -0.006       0.021
sector_sector 68                      0.0097      0.008      1.263      0.207      -0.005       0.025
sector_sector 69                      0.0153      0.012      1.225      0.221      -0.009       0.040
sector_sector 7                      -0.0097      0.008     -1.178      0.239      -0.026       0.006
sector_sector 70                      0.0037      0.009      0.392      0.695      -0.015       0.022
sector_sector 70a                     0.0149      0.010      1.518      0.129      -0.004       0.034
sector_sector 71                     -0.0048      0.007     -0.651      0.515      -0.019       0.010
sector_sector 72                      0.0290      0.008      3.807      0.000       0.014       0.044
sector_sector 73                     -0.0014      0.004     -0.341      0.733      -0.009       0.007
sector_sector 74                      0.0207      0.006      3.253      0.001       0.008       0.033
sector_sector 76                      0.0009      0.006      0.152      0.879      -0.011       0.013
sector_sector 77                     -0.0005      0.007     -0.073      0.942      -0.015       0.014
sector_sector 78                     -0.0050      0.006     -0.825      0.410      -0.017       0.007
sector_sector 79                      0.0107      0.011      0.944      0.345      -0.012       0.033
sector_sector 8                      -0.0147      0.005     -3.020      0.003      -0.024      -0.005
sector_sector 80                     -0.0007      0.004     -0.152      0.879      -0.009       0.008
sector_sector 81                      0.0148      0.012      1.221      0.222      -0.009       0.038
sector_sector 82                     -0.0010      0.009     -0.114      0.909      -0.018       0.016
sector_sector 82a                     0.0093      0.006      1.431      0.152      -0.003       0.022
sector_sector 83                     -0.0030      0.011     -0.280      0.779      -0.024       0.018
sector_sector 84                     -0.0126      0.009     -1.338      0.181      -0.031       0.006
sector_sector 85                      0.0058      0.013      0.434      0.665      -0.020       0.032
sector_sector 86                     -0.0059      0.010     -0.564      0.573      -0.026       0.015
sector_sector 88a                     0.0072      0.007      1.055      0.291      -0.006       0.021
sector_sector 88b                    -0.0004      0.004     -0.098      0.922      -0.008       0.008
sector_sector 89                      0.0015      0.010      0.148      0.883      -0.018       0.021
sector_sector 9                      -0.0148      0.006     -2.634      0.008      -0.026      -0.004
sector_sector 90                     -0.0161      0.012     -1.316      0.188      -0.040       0.008
sector_sector 91                     -0.0012      0.006     -0.197      0.844      -0.013       0.011
sector_sector 92                     -0.0311      0.013     -2.427      0.015      -0.056      -0.006
sector_sector 93                     -0.0050      0.005     -0.976      0.329      -0.015       0.005
sector_sector 95                     -0.0275      0.010     -2.785      0.005      -0.047      -0.008
sector_sector 99                      0.0006      0.006      0.107      0.915      -0.010       0.011
sector_sector 99a                    -0.0149      0.008     -1.946      0.052      -0.030       0.000
sector_sector 9a                     -0.0060      0.005     -1.133      0.257      -0.016       0.004
sector_sohna road                    -0.0317      0.016     -2.041      0.041      -0.062      -0.001
sector_sohna road road               -0.0105      0.005     -1.938      0.053      -0.021       0.000
agePossession_old                    -0.0077      0.005     -1.539      0.124      -0.018       0.002
agePossession_under construction      0.0035      0.004      0.939      0.348      -0.004       0.011
==============================================================================
Omnibus:                      506.470   Durbin-Watson:                   2.040
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4643.103
Skew:                          -0.371   Prob(JB):                         0.00
Kurtosis:                       8.550   Cond. No.                         39.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [30]:
y_log.std()

np.float64(0.5579613263072811)

In [31]:
X_scaled['bedRoom'].std()

np.float64(1.000140716246387)